# Generated by Django 5.2.6 on 2025-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.ImageField(blank=True, default='def_user.png', upload_to='users/'),
        ),
    ]
